import type {
  ProductRow,
  GastosDespacho,
  GastosDespachante,
  GastosAdicionales,
  Impuestos,
  OtroGastoRow,
} from './wizard-types'

export type EstadoOC =
  | 'borrador'
  | 'en_proceso'
  | 'en_transito'
  | 'en_aduana'
  | 'entregada'
  | 'cancelada'

export interface OC {
  id: string
  numeroOC: string
  proveedor: string
  emailProveedor: string
  despachante: string
  emailDespachante: string
  numeroDespacho: string
  estado: EstadoOC
  fecha: string
  llegadaEstimada: string
  notas?: string
}

export interface OCDetalle extends OC {
  referenciaOC: string
  emailsProveedor: string[]
  emailsDespachante: string[]
  despacho: string
  paisOrigen: string
  fechaOC: string
  llegadaEstimada: string
  tipoCambio: string
  divisa: 'ARS/USD' | 'ARS/EUR'
  notas: string
  productos: ProductRow[]
  gastosDespacho: GastosDespacho
  gastosDespachante: GastosDespachante
  gastosAdicionales: GastosAdicionales
  impuestos: Impuestos
  otrosGastos: OtroGastoRow[]
  documentos: {
    facturaProveedor: string | null
    facturaDespachante: string | null
    conocimientoEmbarque: string | null
    certificadoOrigen: string | null
    certificadoAnalisis: string | null
    packingList: string | null
    hojaSeguridad: string | null
    otro: string | null
  }
  otrosDocumentos?: { url: string; slot: string }[]
}

export const MOCK_OCS: OC[] = [
  {
    id: '1',
    numeroOC: 'OC-001',
    proveedor: 'Importadora del Sur',
    emailProveedor: 'proveedor@empresa.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: '',
    estado: 'borrador',
    fecha: '2025-01-15',
    llegadaEstimada: '',
  },
  {
    id: '2',
    numeroOC: 'OC-002',
    proveedor: 'Tech Supplies SA',
    emailProveedor: 'proveedor@empresa.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: '',
    estado: 'en_proceso',
    fecha: '2025-02-03',
    llegadaEstimada: '',
  },
  {
    id: '3',
    numeroOC: 'OC-003',
    proveedor: 'Comercial Andina SRL',
    emailProveedor: 'proveedor@empresa.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: 'D-2025-00341',
    estado: 'en_transito',
    fecha: '2025-03-20',
    llegadaEstimada: '',
  },
  {
    id: '4',
    numeroOC: 'OC-004',
    proveedor: 'Distribuidora Norte',
    emailProveedor: 'proveedor@empresa.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: 'D-2025-00498',
    estado: 'en_aduana',
    fecha: '2025-04-10',
    llegadaEstimada: '',
  },
  {
    id: '5',
    numeroOC: 'OC-005',
    proveedor: 'Global Import Ltda',
    emailProveedor: 'proveedor@empresa.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: 'D-2025-00512',
    estado: 'entregada',
    fecha: '2025-05-05',
    llegadaEstimada: '',
  },
  {
    id: '6',
    numeroOC: 'OC-006',
    proveedor: 'Mercantil del Plata',
    emailProveedor: 'otro@proveedor.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: '',
    estado: 'cancelada',
    fecha: '2025-06-18',
    llegadaEstimada: '',
  },
  {
    id: '7',
    numeroOC: 'OC-007',
    proveedor: 'Exportaciones Cuyanas',
    emailProveedor: 'otro@proveedor.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: '',
    estado: 'borrador',
    fecha: '2025-07-22',
    llegadaEstimada: '',
  },
  {
    id: '8',
    numeroOC: 'OC-008',
    proveedor: 'Pacific Trade Co',
    emailProveedor: 'otro@proveedor.com',
    despachante: 'Despachos del Sur SRL',
    emailDespachante: 'otro@despacho.com',
    numeroDespacho: '',
    estado: 'en_proceso',
    fecha: '2025-08-14',
    llegadaEstimada: '',
  },
  {
    id: '9',
    numeroOC: 'OC-009',
    proveedor: 'Inversiones del Litoral',
    emailProveedor: 'otro@proveedor.com',
    despachante: 'Despachos del Sur SRL',
    emailDespachante: 'otro@despacho.com',
    numeroDespacho: 'D-2025-00887',
    estado: 'en_transito',
    fecha: '2025-09-30',
    llegadaEstimada: '',
  },
  {
    id: '10',
    numeroOC: 'OC-010',
    proveedor: 'Sudamérica Cargo SA',
    emailProveedor: 'otro@proveedor.com',
    despachante: 'Despachos del Sur SRL',
    emailDespachante: 'otro@despacho.com',
    numeroDespacho: 'D-2025-00934',
    estado: 'entregada',
    fecha: '2025-12-01',
    llegadaEstimada: '',
  },
]

const emptyGastosDespacho: GastosDespacho = { sim: '', derechos: '', otros: '', tasaEstadistica: '' }
const emptyGastosDespachante: GastosDespachante = {
  terminal: '',
  fleteInternacional: '',
  fleteInterno: '',
  senasa: '',
  despachante: '',
  gastosOperativos: '',
  gastosBancarios: '',
}
const emptyGastosAdicionales: GastosAdicionales = {
  depositoFiscal: '',
  digitalizacion: '',
  estanciaCamion: '',
}
const emptyImpuestos: Impuestos = { iva: '', ivaAd: '', iibb: '', iigg: '' }
const emptyDocumentos = {
  facturaProveedor: null,
  facturaDespachante: null,
  conocimientoEmbarque: null,
  certificadoOrigen: null,
  certificadoAnalisis: null,
  packingList: null,
  hojaSeguridad: null,
  otro: null,
}

export const MOCK_OCS_DETALLE: OCDetalle[] = [
  {
    id: '1',
    numeroOC: 'OC-001',
    proveedor: 'Importadora del Sur',
    emailProveedor: 'proveedor@empresa.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: '',
    estado: 'borrador',
    fecha: '2025-01-15',
    referenciaOC: 'OC-001',
    emailsProveedor: ['proveedor@empresa.com'],
    emailsDespachante: ['despachante@logistica.com'],
    despacho: '',
    paisOrigen: '',
    fechaOC: '15/01/2025',
    llegadaEstimada: '',
    tipoCambio: '1200',
    divisa: 'ARS/USD',
    notas: '',
    productos: [],
    gastosDespacho: emptyGastosDespacho,
    gastosDespachante: emptyGastosDespachante,
    gastosAdicionales: emptyGastosAdicionales,
    impuestos: emptyImpuestos,
    otrosGastos: [],
    documentos: emptyDocumentos,
  },
  {
    id: '2',
    numeroOC: 'OC-002',
    proveedor: 'Tech Supplies SA',
    emailProveedor: 'proveedor@empresa.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: '',
    estado: 'en_proceso',
    fecha: '2025-02-03',
    referenciaOC: 'OC-002',
    emailsProveedor: ['proveedor@empresa.com'],
    emailsDespachante: ['despachante@logistica.com'],
    despacho: '',
    paisOrigen: '',
    fechaOC: '03/02/2025',
    llegadaEstimada: '',
    tipoCambio: '1200',
    divisa: 'ARS/USD',
    notas: '',
    productos: [],
    gastosDespacho: emptyGastosDespacho,
    gastosDespachante: emptyGastosDespachante,
    gastosAdicionales: emptyGastosAdicionales,
    impuestos: emptyImpuestos,
    otrosGastos: [],
    documentos: emptyDocumentos,
  },
  {
    id: '3',
    numeroOC: 'OC-003',
    proveedor: 'Comercial Andina SRL',
    emailProveedor: 'proveedor@empresa.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: 'D-2025-00341',
    estado: 'en_transito',
    fecha: '2025-03-20',
    referenciaOC: 'OC-003',
    emailsProveedor: ['proveedor@empresa.com'],
    emailsDespachante: ['despachante@logistica.com'],
    despacho: 'D-2025-00341',
    paisOrigen: 'China',
    fechaOC: '20/03/2025',
    llegadaEstimada: '15/04/2025',
    tipoCambio: '1200',
    divisa: 'ARS/USD',
    notas: 'Carga consolidada. Arribo por puerto de Buenos Aires.',
    productos: [
      { id: 'p1', producto: 'Electrónica industrial', descripcion: 'Módulos de control PLC', cantidad: '100', valorUSD: '45.50' },
      { id: 'p2', producto: 'Cables y conectores', descripcion: 'Cables de comunicación RS-485', cantidad: '500', valorUSD: '4.80' },
      { id: 'p3', producto: 'Sensores de temperatura', descripcion: 'Sensores PT100 industriales', cantidad: '200', valorUSD: '12.25' },
    ],
    gastosDespacho: { sim: '85000', derechos: '320000', otros: '40000', tasaEstadistica: '' },
    gastosDespachante: {
      terminal: '150000',
      fleteInternacional: '3200',
      fleteInterno: '90000',
      senasa: '25000',
      despachante: '180000',
      gastosOperativos: '',
      gastosBancarios: '',
    },
    gastosAdicionales: { depositoFiscal: '60000', digitalizacion: '15000', estanciaCamion: '45000' },
    impuestos: { iva: '1100000', ivaAd: '420000', iibb: '210000', iigg: '95000' },
    otrosGastos: [
      { id: 'o1', descripcion: 'Seguro de carga', monto: '850', divisa: 'USD' },
    ],
    documentos: {
      facturaProveedor: 'factura-andina.pdf',
      facturaDespachante: null,
      conocimientoEmbarque: null,
      certificadoOrigen: null,
      certificadoAnalisis: null,
      packingList: null,
      hojaSeguridad: null,
      otro: null,
    },
  },
  {
    id: '4',
    numeroOC: 'OC-004',
    proveedor: 'Distribuidora Norte',
    emailProveedor: 'proveedor@empresa.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: 'D-2025-00498',
    estado: 'en_aduana',
    fecha: '2025-04-10',
    referenciaOC: 'OC-004',
    emailsProveedor: ['proveedor@empresa.com'],
    emailsDespachante: ['despachante@logistica.com'],
    despacho: 'D-2025-00498',
    paisOrigen: 'Brasil',
    fechaOC: '10/04/2025',
    llegadaEstimada: '05/05/2025',
    tipoCambio: '1200',
    divisa: 'ARS/USD',
    notas: 'Importación directa. En proceso de verificación aduanera.',
    productos: [
      { id: 'p1', producto: 'Maquinaria agrícola', descripcion: 'Bombas hidráulicas de precisión', cantidad: '15', valorUSD: '380.00' },
      { id: 'p2', producto: 'Repuestos maquinaria', descripcion: 'Filtros y sellos de repuesto', cantidad: '300', valorUSD: '8.90' },
    ],
    gastosDespacho: { sim: '85000', derechos: '320000', otros: '40000', tasaEstadistica: '' },
    gastosDespachante: {
      terminal: '150000',
      fleteInternacional: '3200',
      fleteInterno: '90000',
      senasa: '25000',
      despachante: '180000',
      gastosOperativos: '',
      gastosBancarios: '',
    },
    gastosAdicionales: { depositoFiscal: '60000', digitalizacion: '15000', estanciaCamion: '45000' },
    impuestos: { iva: '1100000', ivaAd: '420000', iibb: '210000', iigg: '95000' },
    otrosGastos: [
      { id: 'o1', descripcion: 'Seguro de carga', monto: '650', divisa: 'USD' },
    ],
    documentos: {
      facturaProveedor: 'factura-norte-abril.pdf',
      facturaDespachante: 'factura-despacho-0498.pdf',
      conocimientoEmbarque: null,
      certificadoOrigen: null,
      certificadoAnalisis: null,
      packingList: null,
      hojaSeguridad: null,
      otro: null,
    },
  },
  {
    id: '5',
    numeroOC: 'OC-005',
    proveedor: 'Global Import Ltda',
    emailProveedor: 'proveedor@empresa.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: 'D-2025-00512',
    estado: 'entregada',
    fecha: '2025-05-05',
    referenciaOC: 'OC-005',
    emailsProveedor: ['proveedor@empresa.com'],
    emailsDespachante: ['despachante@logistica.com'],
    despacho: 'D-2025-00512',
    paisOrigen: '',
    fechaOC: '05/05/2025',
    llegadaEstimada: '',
    tipoCambio: '1200',
    divisa: 'ARS/USD',
    notas: '',
    productos: [],
    gastosDespacho: emptyGastosDespacho,
    gastosDespachante: emptyGastosDespachante,
    gastosAdicionales: emptyGastosAdicionales,
    impuestos: emptyImpuestos,
    otrosGastos: [],
    documentos: emptyDocumentos,
  },
  {
    id: '6',
    numeroOC: 'OC-006',
    proveedor: 'Mercantil del Plata',
    emailProveedor: 'otro@proveedor.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: '',
    estado: 'cancelada',
    fecha: '2025-06-18',
    referenciaOC: 'OC-006',
    emailsProveedor: ['otro@proveedor.com'],
    emailsDespachante: ['despachante@logistica.com'],
    despacho: '',
    paisOrigen: '',
    fechaOC: '18/06/2025',
    llegadaEstimada: '',
    tipoCambio: '1200',
    divisa: 'ARS/USD',
    notas: '',
    productos: [],
    gastosDespacho: emptyGastosDespacho,
    gastosDespachante: emptyGastosDespachante,
    gastosAdicionales: emptyGastosAdicionales,
    impuestos: emptyImpuestos,
    otrosGastos: [],
    documentos: emptyDocumentos,
  },
  {
    id: '7',
    numeroOC: 'OC-007',
    proveedor: 'Exportaciones Cuyanas',
    emailProveedor: 'otro@proveedor.com',
    despachante: 'Logística Rápida SA',
    emailDespachante: 'despachante@logistica.com',
    numeroDespacho: '',
    estado: 'borrador',
    fecha: '2025-07-22',
    referenciaOC: 'OC-007',
    emailsProveedor: ['otro@proveedor.com'],
    emailsDespachante: ['despachante@logistica.com'],
    despacho: '',
    paisOrigen: '',
    fechaOC: '22/07/2025',
    llegadaEstimada: '',
    tipoCambio: '1200',
    divisa: 'ARS/USD',
    notas: '',
    productos: [],
    gastosDespacho: emptyGastosDespacho,
    gastosDespachante: emptyGastosDespachante,
    gastosAdicionales: emptyGastosAdicionales,
    impuestos: emptyImpuestos,
    otrosGastos: [],
    documentos: emptyDocumentos,
  },
  {
    id: '8',
    numeroOC: 'OC-008',
    proveedor: 'Pacific Trade Co',
    emailProveedor: 'otro@proveedor.com',
    despachante: 'Despachos del Sur SRL',
    emailDespachante: 'otro@despacho.com',
    numeroDespacho: '',
    estado: 'en_proceso',
    fecha: '2025-08-14',
    referenciaOC: 'OC-008',
    emailsProveedor: ['otro@proveedor.com'],
    emailsDespachante: ['otro@despacho.com'],
    despacho: '',
    paisOrigen: '',
    fechaOC: '14/08/2025',
    llegadaEstimada: '',
    tipoCambio: '1200',
    divisa: 'ARS/USD',
    notas: '',
    productos: [],
    gastosDespacho: emptyGastosDespacho,
    gastosDespachante: emptyGastosDespachante,
    gastosAdicionales: emptyGastosAdicionales,
    impuestos: emptyImpuestos,
    otrosGastos: [],
    documentos: emptyDocumentos,
  },
  {
    id: '9',
    numeroOC: 'OC-009',
    proveedor: 'Inversiones del Litoral',
    emailProveedor: 'otro@proveedor.com',
    despachante: 'Despachos del Sur SRL',
    emailDespachante: 'otro@despacho.com',
    numeroDespacho: 'D-2025-00887',
    estado: 'en_transito',
    fecha: '2025-09-30',
    referenciaOC: 'OC-009',
    emailsProveedor: ['otro@proveedor.com'],
    emailsDespachante: ['otro@despacho.com'],
    despacho: 'D-2025-00887',
    paisOrigen: '',
    fechaOC: '30/09/2025',
    llegadaEstimada: '',
    tipoCambio: '1200',
    divisa: 'ARS/USD',
    notas: '',
    productos: [],
    gastosDespacho: emptyGastosDespacho,
    gastosDespachante: emptyGastosDespachante,
    gastosAdicionales: emptyGastosAdicionales,
    impuestos: emptyImpuestos,
    otrosGastos: [],
    documentos: emptyDocumentos,
  },
  {
    id: '10',
    numeroOC: 'OC-010',
    proveedor: 'Sudamérica Cargo SA',
    emailProveedor: 'otro@proveedor.com',
    despachante: 'Despachos del Sur SRL',
    emailDespachante: 'otro@despacho.com',
    numeroDespacho: 'D-2025-00934',
    estado: 'entregada',
    fecha: '2025-12-01',
    referenciaOC: 'OC-010',
    emailsProveedor: ['otro@proveedor.com'],
    emailsDespachante: ['otro@despacho.com'],
    despacho: 'D-2025-00934',
    paisOrigen: '',
    fechaOC: '01/12/2025',
    llegadaEstimada: '',
    tipoCambio: '1200',
    divisa: 'ARS/USD',
    notas: '',
    productos: [],
    gastosDespacho: emptyGastosDespacho,
    gastosDespachante: emptyGastosDespachante,
    gastosAdicionales: emptyGastosAdicionales,
    impuestos: emptyImpuestos,
    otrosGastos: [],
    documentos: emptyDocumentos,
  },
]
